name: update-cache

on:
  push:
    branches:
      - main
      - libtorch
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:

  apply-patches:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libva-dev libvdpau-dev xkb-data
          sudo pip install conan
          sudo chmod 777 -R /root
          sudo conan remote add imageclibs https://imagec.org:4431/artifactory/api/conan/imageclibs
          sudo conan remote login imageclibs writer -p $CONAN_IMAGEC_ARTIFACTORY_PW
          if [[ -f "/root/.conan2/profiles/default" ]]; then
            echo "Loaded from cache"
          else
            sudo conan profile detect 
            sudo bash -c 'echo -e "[conf]\ntools.system.package_manager:mode=install" >> /root/.conan2/profiles/default'
          fi

      - name: Apply onnx patche
        run: |
          cd recipes/onnx/all
          sudo conan create . --version=1.17.0
          sudo conan upload onnx/1.17.0 -r=imageclibs

      - name: Add openblas 0.3.28
        run: |
          cd recipes/openblas/all
          sudo conan create . --version=0.3.28 --build=missing
          sudo conan upload openblas/0.3.28 -r=imageclibs

      - name: Add openmp 0.8.0
        run: |
          cd recipes/openmp/all
          sudo conan create . --version=system --build=missing
          sudo conan upload openmp/system -r=imageclibs

      - name: Add fbgemm 0.8.0
        run: |
          cd recipes/fbgemm/all
          sudo conan create . --version=0.8.0 --build=missing
          sudo conan upload fbgemm/0.8.0 -r=imageclibs

      - name: Add sleef 3.6.1
        run: |
          cd recipes/sleef/all
          sudo conan create . --version=3.6.1 --build=missing
          sudo conan upload sleef/system -r=imageclibs

      - name: Add lib torch
        run: |
          cd recipes/libtorch/all
          sudo conan create . --version=2.4.0 --build=missing
          sudo conan upload libtorch/2.4.0 -r=imageclibs

  build-linux-cache:
    needs:
      - apply-patches
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libva-dev libvdpau-dev xkb-data
          sudo pip install conan
          sudo chmod 777 -R /root
          sudo conan remote remove conancenter
          sudo conan remote add imageclibs https://imagec.org:4431/artifactory/api/conan/imageclibs
          sudo conan remote add conancenter https://center.conan.io
          sudo conan remote login imageclibs writer -p $CONAN_IMAGEC_ARTIFACTORY_PW

      - name: Build with Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}
        run: |
          if [[ -f "/root/.conan2/profiles/default" ]]; then
            echo "Loaded from cache"
          else
            sudo conan profile detect
            sudo bash -c 'echo -e "[conf]\ntools.system.package_manager:mode=install" >> /root/.conan2/profiles/default'
          fi
          sudo cat /root/.conan2/profiles/default
          sudo chmod 777 -R /root/.conan2

          sudo conan install . --profile profiles/profile_linux --output-folder=build --build=missing --format=json > build.json
          sudo conan list --graph=build.json --format=json > pkglist.json
          sudo conan upload --list=pkglist.json -r=imageclibs -c

  build-macos-cache:
    needs:
      - apply-patches
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}
        run: |
          pip install conan
          conan remote remove conancenter
          conan remote add imageclibs https://imagec.org:4431/artifactory/api/conan/imageclibs
          conan remote add conancenter https://center.conan.io
          conan remote login imageclibs writer -p $CONAN_IMAGEC_ARTIFACTORY_PW

      - name: Build with Conan
        run: |
          if [[ -f "/Users/runner/.conan2/profiles/default" ]]; then
            echo "Loaded from cache"
          else
            conan profile detect
            echo -e "[conf]\ntools.system.package_manager:mode=install" >> /Users/runner/.conan2/profiles/default
          fi
          cat /Users/runner/.conan2/profiles/default
          conan install . --profile profiles/profile_macos --output-folder=build --build=missing --format=json > build.json
          conan list --graph=build.json --format=json > pkglist.json
          conan upload --list=pkglist.json -r=imageclibs -c
      

  build-windows-cache:
    needs:
      - apply-patches
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}    
        run: |
          pip install conan
          conan remote remove conancenter
          conan remote add imageclibs https://imagec.org:4431/artifactory/api/conan/imageclibs
          conan remote add conancenter https://center.conan.io
          conan remote login imageclibs writer -p "$env:CONAN_IMAGEC_ARTIFACTORY_PW"

      - name: Build with Conan    
        run: |
          if (Test-Path "C:\Users\runneradmin\.conan2\profiles\default") {
            Write-Host "Loaded from cache!"
          } else {
            conan profile detect
            Add-Content -Path "C:\Users\runneradmin\.conan2\profiles\default" -Value "[conf]`ntools.system.package_manager:mode=install"
          }
          cat C:\Users\runneradmin\.conan2\profiles\default
          conan install . --profile profiles/profile_win_mingw --output-folder=build --build=missing --format=json > build.json
          conan list --graph=build.json --format=json > pkglist.json
          conan upload --list=pkglist.json -r=imageclibs -c
