name: update-cache

on:
  push:
    branches:
      - main
      - init
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-linux-cache:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libva-dev libvdpau-dev xkb-data
          sudo pip install conan
          sudo chmod 777 -R /root
          sudo conan remote add imageclibs https://imagec.org:4431/artifactory/api/conan/imageclibs
          sudo conan remote login imageclibs writer -p $CONAN_IMAGEC_ARTIFACTORY_PW

      - name: Build with Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}
        run: |
          if [[ -f "/root/.conan2/profiles/default" ]]; then
            echo "Loaded from cache"
          else
            sudo conan profile detect
          fi
          sudo cat /root/.conan2/profiles/default
          sudo chmod 777 -R /root/.conan2

          sudo conan install . --profile profiles/profile_linux --output-folder=build --build=missing --format=json > build.json
          sudo conan list --graph=build.json --format=json > pkglist.json
          sudo conan upload --list=pkglist.json -r=imageclibs -c

  build-macos-cache:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}
        run: |
          pip install conan
          conan remote add imageclibs https://imagec.org:4431/artifactory/api/conan/imageclibs
          conan remote login imageclibs writer -p $CONAN_IMAGEC_ARTIFACTORY_PW

      - name: Build with Conan
        run: |
          if [[ -f "/Users/runner/.conan2/profiles/default" ]]; then
            echo "Loaded from cache"
          else
            conan profile detect
          fi
          cat /Users/runner/.conan2/profiles/default
          conan install . --profile profiles/profile_macos --output-folder=build --build=missing --format=json > build.json
          conan list --graph=build.json --format=json > pkglist.json
          conan upload --list=pkglist.json -r=imageclibs -c

  build-windows-cache:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conan
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Conan
        env:
          CONAN_IMAGEC_ARTIFACTORY_PW: ${{ secrets.CONAN_IMAGEC_ARTIFACTORY_PW }}    
        run: |
          pip install conan
          conan remote add imageclibs https://imagec.org:4431/artifactory/api/conan/imageclibs
          conan remote login imageclibs writer -p "$env:CONAN_IMAGEC_ARTIFACTORY_PW"

      - name: Build with Conan    
        run: |
          if (Test-Path "C:\Users\runneradmin\.conan2\profiles\default") {
            Write-Host "Loaded from cache!"
          } else {
            conan profile detect
          }
          cat C:\Users\runneradmin\.conan2\profiles\default
          conan install . --profile profiles/profile_win_mingw --output-folder=build --build=missing --format=json > build.json
          conan list --graph=build.json --format=json > pkglist.json
          conan upload --list=pkglist.json -r=imageclibs -c

      - name: Build patches
        run: |
          cd recipes/onnx/all
          conan create . --version=1.17.0
          conan upload onnx/1.17.0 -r=imageclibs